version: '3'
services:
  ###
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8082:8080
  ###
  db:
    container_name: mysql_serverq
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: xxxx
      MYSQL_DATABASE: xxxxx
      MYSQL_USER: xxxx
      MYSQL_PASSWORD: xxxx
    ports: 
      - 3306:3306
